### ISSUE TITLE
breeze.bridge.angular.js missing

### ISSUE THREAD

**Issue by mikesigs** [Breeze/breeze.js.samples#32]
I just cloned the samples and found that the breeze.bridge.angulare.js file was missing from the build\libs\js.adapters\ folder. It looks like this cmd file is responsible for copying it into the sample's Scripts folder, but since it's not there, it fails to get the file and the sample is kinda borked.

https://github.com/Breeze/breeze.js.samples/blob/master/net/ODataBreezejsSample/ODataBreezejsSample/getLibs.cmd#L19

**Comment by wardbell** [comment]
Please review the [Breeze release notes](http://www.getbreezenow.com/documentation/release-notes#breeze-client-news) where we explain all of this.

To quote those notes:

>The "breeze.angular" service was promoted to Breeze core as a "bridge" adapter (breeze.bridge.angular.js). It is no longer in Breeze Labs (breeze.angular.js has been removed); note the file name change as well!

Ah but *we did neglect to checkin the new bridge file*. Bit by `.gitignore` which hid the omission. I'm fixing hat just now
