### ISSUE TITLE
yo!! can we please get an NG2 sample with .net Core?

### ISSUE THREAD

**Issue by nigel-dewar** [Breeze/breeze.js.samples#41]
As title says. Can we please get an end to end sample for this? Cheers and love your work! 

Breeze is the BEST!!!

**Comment by nigel-dewar** [comment]
I spent a bit of time looking at the .net core tests but there is lots of stuff in there. Just looking for a simple sample.

**Comment by jtraband** [comment]
We are working on it... Got a lot of other irons in the fire as well...

**Comment by nigel-dewar** [comment]
Thanks for reply. Appreciate u got alot on. Ill close this now. Cheers mate.
